# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xwBEY0QF11tkxJzO8nphbVCkt8Bsaq1
"""

!pip install streamlit